### ISSUE TITLE
功能建议：将将活跃度过滤这一操作，在一开始就进行，而不是将30个岗位搜索出来以后，投递时，再进行活跃度过滤。

### ISSUE THREAD

**Issue by Yionse** [Ocyss/boos-helper#15]
Boss搜索结果最多显示十页，而有些投到最后，30个岗位其实只有1个是活跃的。而该插件则是在投递时进行活跃度过滤。这边建议可以在搜索时，即进行活跃度过滤。
我这边使用了其它的插件，可以看到30个岗位中，只有1个是活跃的。
这样可以大大的提高投递的效率。
![image](https://github.com/Ocyss/boos-helper/assets/65143443/9be728e9-d3e3-4e29-a2e5-00eaea24b808)
实际上，应该只投递这一个就可以了。

**Comment by Ocyss** [comment]
获取活跃度这个要去调用接口才有数据,如果搜索就全部调用,容易被风控,你可以打开控制台看看你那个脚本的请求

现在是先走一边通用过滤(不需要额外请求),通过之后在判断有没有开启需要请求卡片数据(活跃度,岗位详细),进行更一步的过滤,已经优化了
