### ISSUE TITLE
关于自动投递，有一点小想法

### ISSUE THREAD

**Issue by Hermes1030** [Ocyss/boos-helper#16]
1.就是投递时可能无法检测到我已经向该公司发送了消息（之前手动投递的），消息会重复发送
2.在投递时，关于这个频率问题，能否设置成大于10秒或者 范围内的随机数，我感觉这种方式能模拟手动投递的频率，不容易被检测到

不过搞的这个插件挺牛的，致敬！

**Comment by Ocyss** [comment]
1. 通过检测与hr是否为好友(聊过天)能筛选掉
2. 延迟应该能统一进行配置管理,你在配置里面看看?

**Comment by Hermes1030** [comment]
检测HR好友是需要开什么设置吗？

version：0.2.0

**Comment by Hermes1030** [comment]
> 1. 通过检测与hr是否为好友(聊过天)能筛选掉
> 2. 延迟应该能统一进行配置管理,你在配置里面看看?

检测HR好友是需要开什么设置吗？

version：0.2.0

**Comment by Ocyss** [comment]
> > 1. 通过检测与hr是否为好友(聊过天)能筛选掉
> > 2. 延迟应该能统一进行配置管理,你在配置里面看看?
> 
> 检测HR好友是需要开什么设置吗？
> 
> version：0.2.0

忘说了，检测hr还没写。。。

**Comment by Ocyss** [comment]
该问题由 0.2.1 修复

https://github.com/Ocyss/boos-helper/releases/tag/0.2.1
