### ISSUE TITLE
投递显示“无法获取token”有可能是boss更新了

### ISSUE THREAD

**Issue by taikula-shang** [Ocyss/boos-helper#19]
投递显示“无法获取token”有可能是boss更新了，我和我的朋友都这样了，不同的电脑以及IP，我朋友在广西，我在上海都这样，今天7.18号以前还好好的，我觉得有可能是boss更新了，求作者大大更新一下

**Comment by sunny-kobe** [comment]
我也是

**Comment by qecrf** [comment]
同出现相同问题

**Comment by taikula-shang** [comment]
作者大大也在找工作啊,现在是真不好找,害



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 上午9:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ocyss/boos-helper] 投递显示“无法获取token”有可能是boss更新了 (Issue #19)




 
我也是

**Comment by Ocyss** [comment]
该问题由 0.2.1 修复

https://github.com/Ocyss/boos-helper/releases/tag/0.2.1

**Comment by zhiyu1998** [comment]
> 该问题由 0.2.1 修复
> 
> https://github.com/Ocyss/boos-helper/releases/tag/0.2.1

感谢大佬的修复，最近很需要
