### ISSUE TITLE
为何插件无法生效。。。

### ISSUE THREAD

**Issue by diave971** [Ocyss/boos-helper#2]
![屏幕截图 2024-04-17 193450](https://github.com/Ocyss/boos-helper/assets/60306114/95f46562-e5b5-427c-a7c2-6f7114f0614d)

**Comment by Ocyss** [comment]
啊？你这是怎么安装的，目前仅支持油猴

**Comment by diave971** [comment]
等下…我在思考🌝原来这是个油猴脚本么

**Comment by diave971** [comment]
> 啊？你这是怎么安装的，目前只支持油猴
🥲俺知道了

**Comment by Ocyss** [comment]
> 等下…我在思考🌝原来这是个油猴脚本么

我挺好奇的，怎么变成插件装上的。我之前也有考虑编译的时候分几个版本一个油侯版，一个插件版
