### ISSUE TITLE
chatgpt配置不成功

### ISSUE THREAD

**Issue by Johnhpure** [Ocyss/boos-helper#22]
按照配置项提示，已经进行配置。但再投递时，无法使用AI相关功能
配置为chatgpt，使用https://api.deepbricks.ai/时，日志报错：this domain is not a part of the @connect list
配置为阿里千问时，日志无报错，但AI功能不生效。
配置见下图：
![微信图片_20240720192640](https://github.com/user-attachments/assets/569bbe1d-0d65-41a4-8ea8-ed8710eeb46e)
![微信图片_20240720192646](https://github.com/user-attachments/assets/53b51f78-90d8-4e68-89bf-06edd5048908)

**Comment by Ocyss** [comment]
这两个配置从截图上看感觉都没配置对，测试过了么？ 
第一个感觉url就不对，第二个感觉model没配置对

然后你这个报错是说 你的apiurl不在白名单内，尝试在管理器中编辑脚本，然后在编辑器的右边有脚本设置，可以去里面把api地址加到XHR 安全 用户白名单中 试试

**Comment by Johnhpure** [comment]
先说图1的url，我看你的tip是说只用填写域名，https://api.deepbricks.ai/v1/chat/completions
，https://api.deepbricks.ai/v1/
，https://api.deepbricks.ai/。所以你看到的截图，我使用的是不带后缀的配置，实际我将上面几个地址都配置过，测试不通过。
第二个，Model，我也都尝试过，但是还是不行。

**Comment by Ocyss** [comment]
> 先说图1的url，我看你的tip是说只用填写域名，https://api.deepbricks.ai/v1/chat/completions ，https://api.deepbricks.ai/v1/ ，[https://api.deepbricks.ai/。所以你看到的截图，我使用的是不带后缀的配置，实际我将上面几个地址都配置过，测试不通过。](https://api.deepbricks.ai/%E3%80%82%E6%89%80%E4%BB%A5%E4%BD%A0%E7%9C%8B%E5%88%B0%E7%9A%84%E6%88%AA%E5%9B%BE%EF%BC%8C%E6%88%91%E4%BD%BF%E7%94%A8%E7%9A%84%E6%98%AF%E4%B8%8D%E5%B8%A6%E5%90%8E%E7%BC%80%E7%9A%84%E9%85%8D%E7%BD%AE%EF%BC%8C%E5%AE%9E%E9%99%85%E6%88%91%E5%B0%86%E4%B8%8A%E9%9D%A2%E5%87%A0%E4%B8%AA%E5%9C%B0%E5%9D%80%E9%83%BD%E9%85%8D%E7%BD%AE%E8%BF%87%EF%BC%8C%E6%B5%8B%E8%AF%95%E4%B8%8D%E9%80%9A%E8%BF%87%E3%80%82) 第二个，Model，我也都尝试过，但是还是不行。

那就是报错说的，不在白名单，可能油猴改规则了不弹窗让用户选择同意，你手动去添加下白名单
然后通义可能确实有问题吧，之后有空会全部测试并修复

**Comment by Johnhpure** [comment]
![image](https://github.com/user-attachments/assets/b1e747ac-4858-4354-bd60-687f9e6cf793)
这个配置应该是没问题啊

**Comment by Ocyss** [comment]
0.2.2 修复了，可以去测试下，我这边只简单的测了会
