### ISSUE TITLE
能否加一个工作名包含的过滤规则呢

### ISSUE THREAD

**Issue by dqzboy** [Ocyss/boos-helper#24]
因为有时候在BOSS去筛选某个岗位的时候，其实会出来很多与搜索的工作名不一样的岗位（应该是hr投放岗位的时候把一个岗位放在了多个岗位分类里面），而这种的有时候插件就会自动去打招呼

**Comment by Ocyss** [comment]
你是否有好好看过脚本的筛选页面呢？每个按钮都点击过吗？这功能一直都有

**Comment by dqzboy** [comment]
![image](https://github.com/user-attachments/assets/83291f53-5c46-4a4c-bfbd-8620b628bf84)
![image](https://github.com/user-attachments/assets/21054285-dba2-41a0-b59b-809fb961e25c)

不好意思 确实我是没有找到 工作名包含  这个匹配规则在哪里

**Comment by Ocyss** [comment]
排除是可以点击的~

**Comment by kokojacket** [comment]
@Ocyss 建议工作名排除和包含可以分开，同时选中。比如想要包含“剪辑”工作名，排除“编导”工作名。如果遇到“编导剪辑”这样的工作，就可以排除了

**Comment by Ocyss** [comment]
少数需求， 分开复杂度就会上去，给小白看那么多配置项不太好。
后续看看要不要支持个正则表达式啥的
