### ISSUE TITLE
自定义打招呼 不生效 

### ISSUE THREAD

**Issue by ouzhaoyuan** [Ocyss/boos-helper#4]
![1713374805220](https://github.com/Ocyss/boos-helper/assets/52497902/7184d787-3003-4862-8159-2eb8030e7a7d)
 不知道是不是这里就不正常了 能批量投递 但是只能招呼语不能自定义 我用的chorme浏览器 是我用的办法有无问题吗

**Comment by Ocyss** [comment]
一般不会，下面是几个选项按钮挺多人没有的，这个待排查。然后你可以试试AI招呼语能不能发送成功，因为我发布只测试了AI那一部分，自定义招呼语可能在改其他部分的时候出bug了，会抓紧修的

**Comment by Ocyss** [comment]
已经发布紧急更新的版本了，可以测试下。https://github.com/Ocyss/boos-helper/releases/tag/0.1.6-fix

**Comment by ouzhaoyuan** [comment]
> 已经发布紧急更新的版本了，可以测试下。https://github.com/Ocyss/boos-helper/releases/tag/0.1.6-fix

好，谢谢 我下班去试试
