### ISSUE TITLE
薪资筛选不生效

### ISSUE THREAD

**Issue by WDD-4ms** [Ocyss/boos-helper#5]
设定薪资5-8k，日志就会出现“rangeMatch is not defined”，将符合和不符合的全部筛掉。
AI打招呼生成发给boss的话之后带有“这是ai生成的内容仅供参考”是故意为之嘛？

**Comment by WDD-4ms** [comment]
![微信截图_20240418163520](https://github.com/Ocyss/boos-helper/assets/159221017/b8255397-40d7-49b2-9a1d-18e121a232e2)
![微信截图_20240418163538](https://github.com/Ocyss/boos-helper/assets/159221017/e43f9ad5-54b4-4f8e-b9f4-ac5381dc8257)
设定7-9k 卡片内薪资有7-9k的也会被筛掉

**Comment by Ocyss** [comment]
薪资这个后面会修改下的,文档也会补全.

> AI招呼语也还在写,所以测试版就先让用户自己写提示词了.

你可以自己选择要不要最后一句话,只是避免些风险,万一AI说错话,到时候面试你又不会不就更尴尬

当然你用gpt4,或者自己写一个好点的提示词就行了

**Comment by Ocyss** [comment]
rangeMatch is not defined 是个bug下个版本修复
> 就是函数拆分后忘记导入了,但挺纳闷的ts居然不给我报错

**Comment by WDD-4ms** [comment]
> rangeMatch is not defined 是个bug下个版本修复
> 
> > 就是函数拆分后忘记导入了,但挺纳闷的ts居然不给我报错

好嘞，感谢老哥修复
