### ISSUE TITLE
请加一个猎头职位屏蔽，非常需要！

### ISSUE THREAD

**Issue by zeketao** [Ocyss/boos-helper#6]
谢谢作者的开发，大龄找工作实在是太难了。如果是企业HR，还有可能考虑我，但猎头职位直接不符合他们的画像，所以非常需要这个功能，感谢！

**Comment by Ocyss** [comment]
#7 已经实现了，但可能要等下个大版本更新0.2.1
> 下个大版本会更加完善，增加更多功能，和更舒服的外观，预计这周发布
