### ISSUE TITLE
希望添加一个 显示岗位发布时间的的功能

### ISSUE THREAD

**Issue by PromiseAll** [Ocyss/boos-helper#9]
![image](https://github.com/Ocyss/boos-helper/assets/56338627/8b2d15fd-cb4c-43d7-a134-6328720bad4f)
参考https://juejin.cn/post/7363164068910071834?searchId=20240430171049ABD221919D5B60A4FDAB

**Comment by smallbonelu** [comment]
boss接口中已经隐藏这个时间字段了

**Comment by Ocyss** [comment]
是的，boos里面删除了
目前和时间有关的可能是企业的图片和boos的头像里面带个日期，但提取还是显示都麻烦，而且作用也不大，如果有新方法能获取岗位时间，我有空就会更新上去
